services:
  db:
    restart: always
    ports: !reset []
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  app:
    restart: always
    ports: !override
      - "127.0.0.1:3000:3000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
